#!/bin/bash

# Setting up timezone

echo -n "Is this a laptop (y/n)? "
read answer
if echo "$answer" | grep -iq "^y" ;then
    echo Yes
    laptop=1
else
    echo No
    laptop=0
fi

ln -sf /usr/share/zoneinfo/Europe/Tirane /etc/localtime
hwclock --systohc

echo "Starting Installing dependency"
sleep 1
pacman -S xorg-server termite xorg-xinit xorg xterm git xdg-user-dirs zsh ttf-inconsolata linux-headers unzip  networkmanager  network-manager-applet xclip  ttf-dejavu noto-fonts docker --noconfirm docker jq openssh keychain expect alsa-utils pass &&

    # Prepering to install pacaur
echo "Preparing to install pacaur"
sleep 1
## Add User
useradd -m -s /bin/bash strixx
gpasswd -a strixx wheel

## Switching to strixx
su strixx

## Getting pacaur and running makepkg as strixx
git clone https://aur.archlinux.org/cower.git &&
    cd cower && makepkg -i --skipinteg && cd .. &&
    git clone https://aur.archlinux.org/pacaur.git &&
    cd pacaur && makepkg -i --skipinteg &&

    sleep 1



if [[ $laptop = 1 ]]
    echo "Laptop setup"


    # Setting Up Network
    touch /etc/hostname
    echo Strixx_Laptop > /etc/hostname
    echo "127.0.1.1 strixx_laptop.localdomain strixx_laptop" >> /etc/hosts
    # Laptop Setup
    bootctl install
    touch /boot/loader/entries/arch.conf
    echo title Arch Linux >> /boot/loader/entries/arch.conf
    echo linux /vmlinuz-linux >> /boot/loader/entries/arch.conf
    echo initrd /initramfs-linux.img >> /boot/loader/entries/arch.conf
    echo "options root=PARTUUID=$(blkid -s PARTUUID -o value /dev/sdb3) rw" >> /boot/loader/entries/arch.conf

    pacman -S broadcom-wl-dkms --noconfirm

    pacaur -S hid-apple-patched-git-dkms py3status i3-gaps lxappearance b43-firmware --noconfirm

else
    echo "Desktop Setup"

    # Setting Up Network
    touch /etc/hostname
    echo Strixx_Desktop > /etc/hostname
    echo "127.0.1.1 strixx_desktop.localdomain strixx_desktop" >> /etc/hosts
fi

# Install Necessary package

echo "Sleeping 3s"
sleep 3

#Running Pacaur
pacaur -S neovim-git trizen rofi-git gtk-theme-arc-git dunst fasd-git fzf-git notify-send.sh compton volumeicon numix-icon-theme-git --noconfirm

systemctl enable NetworkManger
