#!/bin/sh
i3-msg -t get_marks |
python -c '
import json
import sys
group = sys.argv[1]  + "_"
marks = json.load(sys.stdin);
indices = [int(mark.lstrip(group)) for mark in marks if mark.startswith(group)] or [0]
print(sorted(indices)[-1] + 1)
' "$1" | xargs -I {} i3-msg mark "$1_"{}
