#!/usr/bin/sh
echo -e "${COLOR_CYAN}--- Utility ---"

echo -e "${COLOR_BLUE}yt-a <url> ${COLOR_NC}=> ${COLOR_RED}Download youtube url in mp3"
echo -e "${COLOR_BLUE}yt-v <url> ${COLOR_NC}=> ${COLOR_RED}Download youtube url in webm"

echo -e "${COLOR_BLUE}ps-p ${COLOR_NC}=> ${COLOR_RED}Get nice levels for every process, can be used with grep"

echo ""
echo -e "${COLOR_CYAN}--- Docker ---"

echo -e "${COLOR_BLUE}dcd  ${COLOR_NC}=> ${COLOR_RED}docker-compose down"
echo -e "${COLOR_BLUE}dcu  ${COLOR_NC}=> ${COLOR_RED}docker-compose up -d"

echo -e "${COLOR_BLUE}dex  ${COLOR_NC}=> ${COLOR_RED}docker exec -i -t"
echo -e "${COLOR_BLUE}di   ${COLOR_NC}=> ${COLOR_RED}docker images"
echo -e "${COLOR_BLUE}dip  ${COLOR_NC}=> ${COLOR_RED}docker inspect --format {{ .NetworkSettings.IPAddress }} <Docker container ID>"
echo -e "${COLOR_BLUE}dkd  ${COLOR_NC}=> ${COLOR_RED}docker run -d -P"
echo -e "${COLOR_BLUE}dki  ${COLOR_NC}=> ${COLOR_RED}docker run -i -t -P"
echo -e "${COLOR_BLUE}dl   ${COLOR_NC}=> ${COLOR_RED}docker ps -l -q"
echo -e "${COLOR_BLUE}dpa  ${COLOR_NC}=> ${COLOR_RED}docker ps -a"
echo -e "${COLOR_BLUE}dps  ${COLOR_NC}=> ${COLOR_RED}docker ps"
echo -e "${COLOR_BLUE}drmf ${COLOR_NC}=> ${COLOR_RED}docker stop all && docker rm all"
