#! /usr/bin/sh

# Load
loadavg0=`uptime | awk '{print $10+0}'`
loadavg1=`uptime | awk '{print $11+0}'`
loadavg2=`uptime | awk '{print $12+0}'`

memUsed=`free -m  | grep ^Mem | tr -s ' ' | cut -d ' ' -f 3`
memTotal=`free -m  | grep ^Mem | tr -s ' ' | cut -d ' ' -f 2`

spaceTotal=`df -h /dev/sda2 | tail -1 | awk '{print $2}' | cut -d 'G' -f1`
spaceUsed=`df -h /dev/sda2 | tail -1 | awk '{print $3}' | cut -d 'G' -f1`
percentTotal=`df -h /dev/sda2 | tail -1 | awk '{print $5}' | cut -d 'G' -f1`

echo -e "${COLOR_BLUE}System ${COLOR_NC}=> ${COLOR_RED}`uname -rnm`"
echo -e "${COLOR_BLUE}Avarage Load ${COLOR_NC}=> ${COLOR_RED}$loadavg0 $loadavg1 $loadavg2${COLOR_NC}"
echo -e "${COLOR_BLUE}Mem Used ${COLOR_NC}=> ${COLOR_RED}$memUsed/$memTotal MB"
echo -e "${COLOR_BLUE}Space Used ${COLOR_NC}=> ${COLOR_RED}$percentTotal $spaceUsed/$spaceTotal GB "
echo -e "${COLOR_BLUE}Todo ${COLOR_NC}=> ${COLOR_RED}`wc -l < ~/.todo`"
echo -e "${COLOR_BLUE}Help Command ${COLOR_NC}=> ${COLOR_RED}?"

