#!/bin/bash

ac_adapter=$(acpi -a | cut -d' ' -f3 | cut -d- -f1)
battery=`acpi -b | sed 's/^[^,]*, \([0-9]*\).*$/\1/'`
if [ "$ac_adapter" = "on" ]; then
    find / -type d ! \( -path "*cache*" -o -path "*fonts*" -o -path "*icons*" -o -path "*help*" -o -path "*log*" -o -path "afs" -o -path "var*" -o -path "lib*" -o -path "tmp*" -o -path "proc*" \) > ~/.vifm/fzf-read/locate-dir 2>/dev/null
    find / -type f ! \( -path "*cache*" -o -path "*fonts*" -o -path "*icons*" -o -path "*help*" -o -path "*log*" -o -path "afs" -o -path "var*" -o -path "lib*" -o -path "tmp*" -o -path "proc*" \) > ~/.vifm/fzf-read/locate-file 2>/dev/null
else
    if (( 50<=$battery && $battery<=100 )); then
	echo "Updating locate list"
	find / -size -10M -type d ! \( -path "*cache*" -o -path "*fonts*" -o -path "*icons*" -o -path "*help*" -o -path "*log*" -o -path "afs" -o -path "var*" -o -path "lib*" -o -path "tmp*" -o -path "proc*" -o -path "*undoHistory*" -o -path "*npm*" \) > ~/.vifm/fzf-read/locate-dir 2>/dev/null
	find / -size -10M -type f ! \( -path "*cache*" -o -path "*fonts*" -o -path "*icons*" -o -path "*help*" -o -path "*log*" -o -path "afs" -o -path "var*" -o -path "lib*" -o -path "tmp*" -o -path "proc*" -o -path "*undoHistory*" -o -path "*npm*" \) > ~/.vifm/fzf-read/locate-file 2>/dev/null
	echo "Update finished"
    else
	exit 1
    fi
fi
