#!/bin/bash

ac_adapter=$(acpi -a | cut -d' ' -f3 | cut -d- -f1)
if [ "$ac_adapter" != "off" ]; then
    zip -r /home/strixx/data/linux_backup/Backup.zip /home/strixx/.tmp/tmpBackup/ &
else
    exit 1
fi
